Repository RonRonstation/ronstation, pull requests merged in 2024-11, with the labels that each got.

#122 atmospherics changes
  Content.Shared/Atmos/Atmospherics.cs
  Resources/Prototypes/Atmospherics/gases.yml
Labels: No C#

#123 solar power buff
  Content.Server/Solar/Components/SolarPanelComponent.cs
Labels: Needs Discussion, Undergoing maintainer discussion

#125 regroups chems, some other changes
  Resources/Prototypes/Reagents/chemicals.yml
Labels: No C#

#126 Reverts "regroups chems, some other changes"
  Resources/Prototypes/Reagents/chemicals.yml
Labels: No C#

#128 Add TEG flatpacks and put them on the market.
  Resources/Prototypes/Entities/Structures/Power/Generation/teg.yml
  Resources/Prototypes/Ronstation/Catalog/Cargo/cargo_engines.yml
  Resources/Prototypes/Ronstation/Catalog/Fills/Crates/engines.yml
  Resources/Prototypes/Ronstation/Entities/Objects/Devices/Circuitboards/engines.yml
  Resources/Prototypes/Ronstation/Entities/Objects/Devices/flatpack.yml
Labels: No C#, Status: Needs Review

#129 cloning research
  Resources/Locale/en-US/ronstation/research/technologies.ftl
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Ronstation/Research/civilianservices.yml
Labels: No C#, Status: Needs Review

#131 Shuttle modifications.
  Resources/Maps/Ronstation/Shuttles/emergency_medium.yml
  Resources/Maps/Ronstation/Shuttles/emergency_small.yml
Labels: No C#, Changes: Map

#130 Add spawns for poker cards.
  Resources/Prototypes/Entities/Markers/Spawners/Random/maintenance.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/toy.yml
  Resources/Prototypes/Entities/Objects/Decoration/present.yml
Labels: No C#

#134 opporozidone buff
  Resources/Prototypes/Reagents/medicine.yml
  Resources/Prototypes/Recipes/Reactions/medicine.yml
Labels: Changes: No C#, S: Untriaged, size/XS

#135 gaming
  Resources/Maps/Ronstation/Shuttles/ShuttleEvent/engineering_failure.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/GameRules/unknown_shuttles.yml
  Resources/Prototypes/Recipes/Lathes/sheet.yml
  Resources/Prototypes/Ronstation/Entities/Objects/Devices/Circuitboards/production.yml
  Resources/Prototypes/Ronstation/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Ronstation/Gamerules/unknown_shuttles.yml
  Resources/Prototypes/Ronstation/Recipes/Lathes/electronics.yml
  Resources/Prototypes/Ronstation/Shuttles/shuttle_incoming_event.yml
  Resources/Prototypes/Shuttles/shuttle_incoming_event.yml
Labels: Changes: No C#, S: Needs Review, Changes: Map, size/XL

#137 Derotate Reach.
  Resources/Prototypes/Maps/Pools/default.yml
Labels: Changes: No C#, Changes: Map, P1: High, A: Mapping, size/XS

#136 More lobby art.
  Resources/Prototypes/Ronstation/lobbyscreens.yml
  Resources/Textures/Ronstation/LobbyScreens/attributions.yml
  Resources/Textures/Ronstation/LobbyScreens/error.webp
  Resources/Textures/Ronstation/LobbyScreens/error.webp.yml
Labels: Changes: No C#, S: Needs Review, P2: Low, size/S, A: Art, T: Visual Change

#141 Lobby screens
  Resources/Prototypes/Ronstation/lobbyscreens.yml
  Resources/Textures/Ronstation/LobbyScreens/janitorialduties.webp
  Resources/Textures/Ronstation/LobbyScreens/janitorialduties.webp.yml
  Resources/Textures/Ronstation/LobbyScreens/terminalstation.webp
  Resources/Textures/Ronstation/LobbyScreens/terminalstation.webp.yml
Labels: Changes: No C#, size/S, A: Art

#145 anothe fix
  Resources/Maps/Ronstation/Shuttles/ShuttleEvent/engineering_failure.yml
Labels: T: Bug, Changes: No C#, Changes: Map, Intent: Hotfix, size/L

#143 Updates Saltern-II, Cluster-II, and Atlas-B.
  Resources/Maps/Ronstation/atlas-2.yml
  Resources/Maps/Ronstation/cluster-2.yml
  Resources/Maps/Ronstation/saltern-2.yml
Labels: Changes: No C#, S: Needs Review, Changes: Map, A: Mapping, size/XL

#146 removes engineering failure, it's too much of a failure
  Resources/Maps/Ronstation/Shuttles/ShuttleEvent/engineering_failure.yml
  Resources/Prototypes/GameRules/unknown_shuttles.yml
  Resources/Prototypes/Ronstation/Gamerules/unknown_shuttles.yml
  Resources/Prototypes/Ronstation/Shuttles/shuttle_incoming_event.yml
Labels: Changes: No C#, Changes: Map, A: Mapping, size/XL

#144 Revert 'Remove drag & drop dropping items from containers #32706'.
  Content.Client/UserInterface/Systems/Storage/StorageUIController.cs
  Content.Shared/Storage/EntitySystems/SharedStorageSystem.cs
  Content.Shared/Storage/StorageComponent.cs
Labels: S: Needs Review, P3: Low, Changes: UI, A: UI, size/M

#147 More chemicals part five
  Resources/Locale/en-US/reagents/meta/elements.ftl
  Resources/Locale/en-US/reagents/meta/fun.ftl
  Resources/Locale/en-US/reagents/meta/medicine.ftl
  Resources/Locale/en-US/reagents/meta/narcotics.ftl
  Resources/Prototypes/Catalog/ReagentDispensers/chemical.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/chemvend.yml
  Resources/Prototypes/Entities/Objects/Specific/chemical-containers.yml
  Resources/Prototypes/Reagents/Consumable/Drink/drinks.yml
  Resources/Prototypes/Reagents/chemicals.yml
  Resources/Prototypes/Reagents/elements.yml
  Resources/Prototypes/Reagents/fun.yml
  Resources/Prototypes/Reagents/medicine.yml
  Resources/Prototypes/Reagents/narcotics.yml
  Resources/Prototypes/Reagents/toxins.yml
  Resources/Prototypes/Recipes/Reactions/fun.yml
  Resources/Prototypes/Recipes/Reactions/medicine.yml
Labels: Changes: No C#, P2: Medium, A: Medical, size/L
