Repository RonRonstation/ronstation, pull requests merged in 2024-08, with the labels that each got.

#46 Fixed axing quality lines in tool-qualities.ftl.
  Resources/Locale/en-US/tools/tool-qualities.ftl
Labels: No C#

#53 Raise role timers.
  Resources/Prototypes/Roles/Jobs/Cargo/cargo_technician.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
  Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
  Resources/Prototypes/Roles/Jobs/Medical/chemist.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
  Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
  Resources/Prototypes/Roles/Jobs/Science/borg.yml
  Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
  Resources/Prototypes/Roles/Jobs/Science/scientist.yml
  Resources/Prototypes/Roles/Jobs/Security/detective.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Roles/Jobs/Security/warden.yml
Labels: No C#

#54 Fix syndimothroach texture path in prototypes.
  Resources/Prototypes/Ronstation/Entities/Mobs/NPCs/animals.yml
Labels: No C#

#55 xeno change
  Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
Labels: No C#

#62 Add heccdivers
  Resources/Locale/en-US/ronstation/contraband/contraband-severity.ftl
  Resources/Locale/en-US/ronstation/ghost/roles/ghost-role-component.ftl
  Resources/Prototypes/Ronstation/Access/terragov.yml
  Resources/Prototypes/Ronstation/Entities/Clothing/Head/hardsuit-helmets.yml
  Resources/Prototypes/Ronstation/Entities/Clothing/Neck/cloaks.yml
  Resources/Prototypes/Ronstation/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/Ronstation/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Prototypes/Ronstation/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/Ronstation/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Ronstation/Entities/Objects/Devices/radio.yml
  Resources/Prototypes/Ronstation/Entities/Objects/Misc/identification_cards.yml
  Resources/Prototypes/Ronstation/Entities/Objects/base_contraband.yml
  Resources/Prototypes/Ronstation/Roles/Jobs/Fun/terragov_startinggear.yml
  Resources/Prototypes/Ronstation/contraband_severities.yml
  Resources/Textures/Ronstation/Clothing/Head/Helmets/heccdiver.rsi/equipped-HELMET-vox.png
  Resources/Textures/Ronstation/Clothing/Head/Helmets/heccdiver.rsi/equipped-HELMET.png
  Resources/Textures/Ronstation/Clothing/Head/Helmets/heccdiver.rsi/icon.png
  Resources/Textures/Ronstation/Clothing/Head/Helmets/heccdiver.rsi/inhand-left.png
  Resources/Textures/Ronstation/Clothing/Head/Helmets/heccdiver.rsi/inhand-right.png
  Resources/Textures/Ronstation/Clothing/Head/Helmets/heccdiver.rsi/meta.json
  Resources/Textures/Ronstation/Clothing/Neck/Cloaks/heccdiver.rsi/equipped-NECK.png
  Resources/Textures/Ronstation/Clothing/Neck/Cloaks/heccdiver.rsi/icon.png
  Resources/Textures/Ronstation/Clothing/Neck/Cloaks/heccdiver.rsi/inhand-left.png
  Resources/Textures/Ronstation/Clothing/Neck/Cloaks/heccdiver.rsi/inhand-right.png
  Resources/Textures/Ronstation/Clothing/Neck/Cloaks/heccdiver.rsi/meta.json
  Resources/Textures/Ronstation/Clothing/OuterClothing/Hardsuits/heccdiver.rsi/equipped-OUTERCLOTHING-vox.png
  Resources/Textures/Ronstation/Clothing/OuterClothing/Hardsuits/heccdiver.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Ronstation/Clothing/OuterClothing/Hardsuits/heccdiver.rsi/icon.png
  Resources/Textures/Ronstation/Clothing/OuterClothing/Hardsuits/heccdiver.rsi/inhand-left.png
  Resources/Textures/Ronstation/Clothing/OuterClothing/Hardsuits/heccdiver.rsi/inhand-right.png
  Resources/Textures/Ronstation/Clothing/OuterClothing/Hardsuits/heccdiver.rsi/meta.json
  Resources/Textures/Ronstation/Clothing/Uniforms/Jumpsuit/heccdiver.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/Ronstation/Clothing/Uniforms/Jumpsuit/heccdiver.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Ronstation/Clothing/Uniforms/Jumpsuit/heccdiver.rsi/icon.png
  Resources/Textures/Ronstation/Clothing/Uniforms/Jumpsuit/heccdiver.rsi/inhand-left.png
  Resources/Textures/Ronstation/Clothing/Uniforms/Jumpsuit/heccdiver.rsi/inhand-right.png
  Resources/Textures/Ronstation/Clothing/Uniforms/Jumpsuit/heccdiver.rsi/meta.json
  Resources/Textures/Ronstation/Objects/Devices/pda.rsi/equipped-BELT.png
  Resources/Textures/Ronstation/Objects/Devices/pda.rsi/equipped-IDCARD.png
  Resources/Textures/Ronstation/Objects/Devices/pda.rsi/id_overlay.png
  Resources/Textures/Ronstation/Objects/Devices/pda.rsi/inhand-left.png
  Resources/Textures/Ronstation/Objects/Devices/pda.rsi/inhand-right.png
  Resources/Textures/Ronstation/Objects/Devices/pda.rsi/insert_overlay.png
  Resources/Textures/Ronstation/Objects/Devices/pda.rsi/light_overlay.png
  Resources/Textures/Ronstation/Objects/Devices/pda.rsi/meta.json
  Resources/Textures/Ronstation/Objects/Devices/pda.rsi/pda-heccdiver.png
  Resources/Textures/Ronstation/Objects/Devices/pda.rsi/pda.png
  Resources/Textures/Ronstation/Objects/Devices/terragovhandy.rsi/meta.json
  Resources/Textures/Ronstation/Objects/Devices/terragovhandy.rsi/walkietalkie-inhand-left.png
  Resources/Textures/Ronstation/Objects/Devices/terragovhandy.rsi/walkietalkie-inhand-right.png
  Resources/Textures/Ronstation/Objects/Devices/terragovhandy.rsi/walkietalkie-off.png
  Resources/Textures/Ronstation/Objects/Devices/terragovhandy.rsi/walkietalkie-on.png
  Resources/Textures/Ronstation/Objects/Devices/terragovhandy.rsi/walkietalkie.png
  Resources/Textures/Ronstation/Objects/Misc/id_cards.rsi/heccdiver-inhand-left.png
  Resources/Textures/Ronstation/Objects/Misc/id_cards.rsi/heccdiver-inhand-right.png
  Resources/Textures/Ronstation/Objects/Misc/id_cards.rsi/heccdiver.png
  Resources/Textures/Ronstation/Objects/Misc/id_cards.rsi/meta.json
Labels: Changes: Sprites, No C#

#59 Reduced artifact scary explosion intensity.
  Resources/Prototypes/XenoArch/Effects/normal_effects.yml
Labels: No C#

#61 Add a slightly redesigned Saltern, Saltern-2.
  Resources/Maps/Ronstation/saltern-2.yml
  Resources/Prototypes/Ronstation/Maps/saltern-2.yml
Labels: No C#, Changes: Map

#64 Fix CLRF error and allow Saltern-II to be voted upon.
  Content.Benchmarks/MapLoadBenchmark.cs
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Maps/Ronstation/saltern-2.yml
  Resources/Prototypes/Maps/Pools/default.yml
  Resources/Prototypes/Ronstation/Maps/saltern-2.yml
Labels: Changes: Map

#66 Fix sprites of heccdiver helmets.
  Resources/Textures/Ronstation/Clothing/Head/Helmets/heccdiver.rsi/equipped-HELMET-vox.png
  Resources/Textures/Ronstation/Clothing/Head/Helmets/heccdiver.rsi/equipped-HELMET.png
Labels: Changes: Sprites, No C#

#67 Readded Atlas and Cluster.
  Content.Benchmarks/MapLoadBenchmark.cs
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Maps/Ronstation/atlas-2.yml
  Resources/Maps/Ronstation/cluster-2.yml
  Resources/Prototypes/Maps/Pools/default.yml
  Resources/Prototypes/Ronstation/Maps/atlas-2.yml
  Resources/Prototypes/Ronstation/Maps/cluster-2.yml
Labels: Changes: Map

#65 Readd emergency nitrogen tanks, and replace oxygen tanks with air tanks.
  Resources/Prototypes/Catalog/Fills/Items/toolboxes.yml
  Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml
  Resources/Prototypes/Catalog/Fills/Lockers/engineer.yml
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Catalog/Fills/Lockers/misc.yml
  Resources/Prototypes/Catalog/Fills/Lockers/security.yml
  Resources/Prototypes/Catalog/Fills/Lockers/suit_storage.yml
  Resources/ServerInfo/Guidebook/Mobs/SlimePerson.xml
Labels: No C#
