Repository RonRonstation/ronstation, pull requests merged in 2024-09, with the labels that each got.

#68 Added blueshield role.
  Resources/Locale/en-US/ronstation/job/job-description.ftl
  Resources/Locale/en-US/ronstation/job/job-names.ftl
  Resources/Locale/en-US/ronstation/preferences/loadout-groups.ftl
  Resources/Maps/Ronstation/atlas-2.yml
  Resources/Maps/Ronstation/cluster-2.yml
  Resources/Maps/Ronstation/saltern-2.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Prototypes/Ronstation/Entities/Clothing/Uniforms/jumpskirts.yml
  Resources/Prototypes/Ronstation/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Prototypes/Ronstation/Entities/Markers/Spawners/jobs.yml
  Resources/Prototypes/Ronstation/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Ronstation/Entities/Objects/Misc/identification_cards.yml
  Resources/Prototypes/Ronstation/Loadouts/Jobs/Command/blueshield_officer.yml
  Resources/Prototypes/Ronstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/Ronstation/Loadouts/role_loadouts.yml
  Resources/Prototypes/Ronstation/Maps/atlas-2.yml
  Resources/Prototypes/Ronstation/Maps/cluster-2.yml
  Resources/Prototypes/Ronstation/Maps/saltern-2.yml
  Resources/Prototypes/Ronstation/Roles/Jobs/Command/blueshield_officer.yml
  Resources/Prototypes/Ronstation/Roles/play_time_trackers.yml
  Resources/Textures/Ronstation/Clothing/Uniforms/Jumpskirt/blueshield_grey.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/Ronstation/Clothing/Uniforms/Jumpskirt/blueshield_grey.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Ronstation/Clothing/Uniforms/Jumpskirt/blueshield_grey.rsi/icon.png
  Resources/Textures/Ronstation/Clothing/Uniforms/Jumpskirt/blueshield_grey.rsi/inhand-left.png
  Resources/Textures/Ronstation/Clothing/Uniforms/Jumpskirt/blueshield_grey.rsi/inhand-right.png
  Resources/Textures/Ronstation/Clothing/Uniforms/Jumpskirt/blueshield_grey.rsi/meta.json
  Resources/Textures/Ronstation/Clothing/Uniforms/Jumpsuit/blueshield_grey.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/Ronstation/Clothing/Uniforms/Jumpsuit/blueshield_grey.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Ronstation/Clothing/Uniforms/Jumpsuit/blueshield_grey.rsi/icon.png
  Resources/Textures/Ronstation/Clothing/Uniforms/Jumpsuit/blueshield_grey.rsi/inhand-left.png
  Resources/Textures/Ronstation/Clothing/Uniforms/Jumpsuit/blueshield_grey.rsi/inhand-right.png
  Resources/Textures/Ronstation/Clothing/Uniforms/Jumpsuit/blueshield_grey.rsi/meta.json
  Resources/Textures/Ronstation/Markers/jobs.rsi/blueshield_officer.png
  Resources/Textures/Ronstation/Markers/jobs.rsi/green.png
  Resources/Textures/Ronstation/Markers/jobs.rsi/meta.json
  Resources/Textures/Ronstation/Objects/Devices/pda.rsi/meta.json
  Resources/Textures/Ronstation/Objects/Devices/pda.rsi/pda-blueshield.png
  Resources/Textures/Ronstation/Objects/Misc/id_cards.rsi/default-inhand-left.png
  Resources/Textures/Ronstation/Objects/Misc/id_cards.rsi/default-inhand-right.png
  Resources/Textures/Ronstation/Objects/Misc/id_cards.rsi/default.png
  Resources/Textures/Ronstation/Objects/Misc/id_cards.rsi/idnanotrasen.png
  Resources/Textures/Ronstation/Objects/Misc/id_cards.rsi/meta.json
Labels: Changes: Sprites, No C#, Needs Discussion, Changes: Map

#70 Readded salvage shuttle.
  Resources/Prototypes/Entities/Stations/base.yml
  Resources/Prototypes/Ronstation/Entities/Objects/Devices/Circuitboards/computer.yml
  Resources/Prototypes/Ronstation/Entities/Structures/Machines/Computers/computers.yml
  Resources/Prototypes/Ronstation/Objectives/stealTargetGroups.yml
  Resources/Prototypes/Ronstation/Objectives/thief.yml
  Resources/migration.yml
Labels: No C#

#71 Goliath debuff
  Resources/Prototypes/Entities/Mobs/NPCs/asteroid.yml
Labels: No C#

#73 Readd fluffy hair.
  Resources/Locale/en-US/ronstation/accessories/human-hair.ftl
  Resources/Prototypes/Ronstation/Entities/Mobs/Customization/Markings/human_hair.yml
  Resources/Textures/Ronstation/Mobs/Customization/human_hair.rsi/fluffyhair.png
  Resources/Textures/Ronstation/Mobs/Customization/human_hair.rsi/meta.json
Labels: Changes: Sprites, No C#

#72 Update space.yml - Snail blood to blue blood
  Resources/Prototypes/Entities/Mobs/NPCs/space.yml
Labels: No C#

#76 Makes certain events less common
  Resources/Prototypes/GameRules/events.yml
Labels: No C#

#75 Make pest migration chances lower
  Resources/Prototypes/GameRules/pests.yml
Labels: No C#

#74 Saltern-II: Update
  Resources/Maps/Ronstation/saltern-2.yml
  Resources/Prototypes/Ronstation/Maps/saltern-2.yml
Labels: No C#, Changes: Map

#85 Saltern-II: Fix atmos gas chambers and other updates.
  Resources/Maps/Ronstation/saltern-2.yml
Labels: No C#, Changes: Map

#84 Allow atmos fire-axe to pry plating.
  Resources/Locale/en-US/tools/tool-qualities.ftl
  Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml
  Resources/Prototypes/Tiles/plating.yml
  Resources/Prototypes/tool_qualities.yml
Labels: No C#

#81 Fix salvage shuttle localization issue.
  Resources/Locale/en-US/ronstation/objectives/conditions/steal-target-groups.ftl
  Resources/Prototypes/Ronstation/Objectives/stealTargetGroups.yml
Labels: No C#, PR: Bug fix

#78 Replace Substation and APC sprites.
  Content.Client/Power/APC/ApcVisualizerComponent.cs
  Resources/Prototypes/Entities/Structures/Power/apc.yml
  Resources/Prototypes/Entities/Structures/Power/substation.yml
  Resources/Textures/Ronstation/Structures/Power/apc.rsi/base.png
  Resources/Textures/Ronstation/Structures/Power/apc.rsi/broken.png
  Resources/Textures/Ronstation/Structures/Power/apc.rsi/display-charging.png
  Resources/Textures/Ronstation/Structures/Power/apc.rsi/display-full.png
  Resources/Textures/Ronstation/Structures/Power/apc.rsi/display-lack.png
  Resources/Textures/Ronstation/Structures/Power/apc.rsi/display-remote.png
  Resources/Textures/Ronstation/Structures/Power/apc.rsi/emag-unlit.png
  Resources/Textures/Ronstation/Structures/Power/apc.rsi/frame.png
  Resources/Textures/Ronstation/Structures/Power/apc.rsi/lock0-locked.png
  Resources/Textures/Ronstation/Structures/Power/apc.rsi/lock1-locked.png
  Resources/Textures/Ronstation/Structures/Power/apc.rsi/meta.json
  Resources/Textures/Ronstation/Structures/Power/apc.rsi/panel.png
  Resources/Textures/Ronstation/Structures/Power/apc.rsi/sparks-unlit.png
  Resources/Textures/Ronstation/Structures/Power/apc.rsi/static.png
  Resources/Textures/Ronstation/Structures/Power/substation.rsi/charging.png
  Resources/Textures/Ronstation/Structures/Power/substation.rsi/dead.png
  Resources/Textures/Ronstation/Structures/Power/substation.rsi/full.png
  Resources/Textures/Ronstation/Structures/Power/substation.rsi/meta.json
  Resources/Textures/Ronstation/Structures/Power/substation.rsi/screen.png
  Resources/Textures/Ronstation/Structures/Power/substation.rsi/screen_wall.png
  Resources/Textures/Ronstation/Structures/Power/substation.rsi/substation.png
  Resources/Textures/Ronstation/Structures/Power/substation.rsi/substation_static.png
  Resources/Textures/Ronstation/Structures/Power/substation.rsi/substation_wall.png
  Resources/Textures/Ronstation/Structures/Power/substation.rsi/substation_wall_static.png
Labels: Changes: Sprites

#86 Make closet skeletons non-antagonists.
  Resources/Locale/en-US/ronstation/ghost/roles/ghost-role-component.ftl
  Resources/Prototypes/Entities/Mobs/Player/skeleton.yml
  Resources/Prototypes/Ronstation/Roles/Jobs/Fun/misc_startinggear.yml
Labels: No C#

#88 AI names
  Resources/Prototypes/Datasets/Names/ai.yml
Labels: No C#

#93 Ammoniated Sludge
  Resources/Locale/en-US/reagents/meta/fun.ftl
  Resources/Prototypes/Reagents/fun.yml
  Resources/Prototypes/Recipes/Reactions/fun.yml
Labels: No C#, Needs Discussion

#96 Adds ammoniated sludge to variation.yml
  Resources/Prototypes/GameRules/variation.yml
Labels: No C#

#99 Calomel and Ammoniated Mercury
  Resources/Locale/en-US/reagents/meta/chemicals.ftl
  Resources/Prototypes/Reagents/chemicals.yml
  Resources/Prototypes/Recipes/Reactions/chemicals.yml
  Resources/Prototypes/Recipes/Reactions/fun.yml
Labels: No C#

#87 Rework firelocks.
  Resources/Prototypes/Catalog/Fills/Lockers/engineer.yml
  Resources/Prototypes/Entities/Structures/Doors/Firelocks/firelock.yml
  Resources/Prototypes/Ronstation/Access/engineering.yml
  Resources/Prototypes/Ronstation/Entities/Objects/Devices/door_remote.yml
  Resources/migration.yml
Labels: No C#

#95 Cluster-2: Update.
  Resources/Maps/Ronstation/cluster-2.yml
  Resources/Prototypes/Ronstation/Maps/cluster-2.yml
Labels: No C#, Changes: Map
