Repository RonRonstation/ronstation, pull requests merged in 2024-10, with the labels that each got.

#100 Tweaks strange pills
  Resources/Prototypes/Entities/Objects/Specific/Medical/randompill.yml
Labels: No C#

#103 metabolism rate for ammoniated sludge
  Resources/Prototypes/Reagents/fun.yml
Labels: No C#

#101 Space Mushroom changes
  Resources/Locale/en-US/reagents/meta/medicine.ftl
  Resources/Locale/en-US/reagents/meta/toxins.ftl
  Resources/Prototypes/Entities/Objects/Misc/spaceshroom.yml
  Resources/Prototypes/Reagents/medicine.yml
  Resources/Prototypes/Reagents/toxins.yml
  Resources/Prototypes/Recipes/Reactions/medicine.yml
  Resources/Textures/Objects/Misc/spaceshroom.rsi/meta.json
  Resources/Textures/Objects/Misc/spaceshroom.rsi/object.png
  Resources/Textures/Objects/Misc/spaceshroom.rsi/spaceshroom_cooked.png
  Resources/Textures/Objects/Misc/spaceshroom.rsi/structure.png
Labels: Changes: Sprites, No C#

#107 more chemistry
  Resources/Locale/en-US/reagents/meta/botany.ftl
  Resources/Locale/en-US/reagents/meta/narcotics.ftl
  Resources/Locale/en-US/reagents/meta/toxins.ftl
  Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml
  Resources/Prototypes/Hydroponics/randomChemicals.yml
  Resources/Prototypes/Reagents/botany.yml
  Resources/Prototypes/Reagents/narcotics.yml
  Resources/Prototypes/Reagents/toxins.yml
  Resources/Prototypes/Recipes/Reactions/botany.yml
  Resources/Prototypes/Recipes/Reactions/chemicals.yml
  Resources/Prototypes/Recipes/Reactions/fun.yml
Labels: No C#

#98 Remade shuttles for Cluster-2, Atlas-B, and Saltern-2.
  Resources/Maps/Ronstation/Shuttles/emergency_medium.yml
  Resources/Maps/Ronstation/Shuttles/emergency_small.yml
  Resources/Prototypes/Ronstation/Maps/atlas-2.yml
  Resources/Prototypes/Ronstation/Maps/cluster-2.yml
  Resources/Prototypes/Ronstation/Maps/saltern-2.yml
Labels: No C#, Changes: Map

#109 Give blueshield brig access while fixing blueshield uniform names, as well as adding blueshield as a ghost role.
  Resources/Locale/en-US/ronstation/ghost/roles/ghost-role-component.ftl
  Resources/Locale/en-US/ronstation/job/job-description.ftl
  Resources/Locale/en-US/ronstation/job/job-names.ftl
  Resources/Prototypes/Ronstation/Entities/Clothing/Uniforms/jumpskirts.yml
  Resources/Prototypes/Ronstation/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Prototypes/Ronstation/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/Ronstation/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Ronstation/Entities/Objects/Misc/identification_cards.yml
  Resources/Prototypes/Ronstation/Roles/Jobs/CentCom/centcomblueshield.yml
  Resources/Prototypes/Ronstation/Roles/Jobs/Command/blueshield_officer.yml
  Resources/Prototypes/Ronstation/Roles/play_time_trackers.yml
Labels: No C#

#113 goliath rebalance
  Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml
  Resources/Prototypes/Entities/Mobs/NPCs/asteroid.yml
  Resources/Prototypes/NPCs/goliath.yml
Labels: No C#

#110 more reactions
  Resources/Locale/en-US/reagents/meta/chemicals.ftl
  Resources/Locale/en-US/reagents/meta/fun.ftl
  Resources/Prototypes/Reagents/chemicals.yml
  Resources/Prototypes/Reagents/fun.yml
  Resources/Prototypes/Reagents/medicine.yml
  Resources/Prototypes/Recipes/Reactions/chemicals.yml
  Resources/Prototypes/Recipes/Reactions/fun.yml
Labels: No C#

#111 Fix prototypes and adds poker cards to gaming vending machine
  Resources/Prototypes/Catalog/VendingMachines/Inventories/games.yml
  Resources/Prototypes/Ronstation/Entities/Catalog/Fills/Items/card_box.yml
  Resources/Prototypes/Ronstation/Entities/Objects/Fun/Tabletop/Cards/card_box.yml
  Resources/Prototypes/Ronstation/Entities/Objects/Fun/Tabletop/Cards/poker.yml
  Resources/Prototypes/Ronstation/tags.yml
Labels: No C#

#115 Fitted another 15 kilowatts generator to the NT Evac Small shuttle.
  Resources/Maps/Ronstation/Shuttles/emergency_small.yml
Labels: No C#, Priority: 1-Urgent, Changes: Map

#117 Update.
  Content.Server/EntityEffects/Effects/FlashReactionEffect.cs
  Resources/Changelog/Changelog.yml
  Resources/Locale/en-US/guidebook/chemistry/effects.ftl
  Resources/Maps/Test/dev_map.yml
  Resources/Prototypes/Entities/Effects/chemistry_effects.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/Containers/bowl.yml
  Resources/Prototypes/Entities/Structures/Piping/Atmospherics/miners.yml
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/GameRules/unknown_shuttles.yml
  Resources/Prototypes/Recipes/Reactions/chemicals.yml
  Resources/Prototypes/Shuttles/shuttle_incoming_event.yml
Labels: Changes: Sprites, Changes: Map

#114 base point source in cargo, orderable rnd servers, autolathe/protolathe/circuitimprinter flatpacks at cargo
  Resources/Prototypes/Catalog/Cargo/cargo_science.yml
  Resources/Prototypes/Catalog/Fills/Crates/science.yml
  Resources/Prototypes/Entities/Structures/Machines/research.yml
  Resources/Prototypes/Ronstation/Catalog/Cargo/cargo_science.yml
  Resources/Prototypes/Ronstation/Catalog/Fills/Crates/science.yml
  Resources/Prototypes/Ronstation/Entities/Objects/Devices/flatpack.yml
  Resources/Textures/Ronstation/Objects/Specific/Research/researchdisk.rsi/10kdisk.png
  Resources/Textures/Ronstation/Objects/Specific/Research/researchdisk.rsi/5kdisk.png
  Resources/Textures/Ronstation/Objects/Specific/Research/researchdisk.rsi/meta.json
Labels: Changes: Sprites, No C#, Needs Discussion, Undergoing maintainer discussion

#116 Make firebots and janibots targets of sentience events.
  Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml
Labels: No C#, Needs Discussion, Undergoing maintainer discussion

#119 Update.
  Content.Client/HealthAnalyzer/UI/HealthAnalyzerWindow.xaml
  Content.Client/HealthAnalyzer/UI/HealthAnalyzerWindow.xaml.cs
  Content.Server/Medical/CryoPodSystem.cs
  Content.Server/Medical/HealthAnalyzerSystem.cs
  Content.Server/Nutrition/EntitySystems/CreamPieSystem.cs
  Content.Shared/MedicalScanner/HealthAnalyzerScannedUserMessage.cs
  Resources/Changelog/Changelog.yml
  Resources/Credits/GitHub.txt
  Resources/Locale/en-US/medical/components/health-analyzer-component.ftl
  Resources/Prototypes/Datasets/Names/last.yml
Labels: Changes: Map, Changes: UI

#120 Replace air tanks in lockers with oxygen and nitrogen tanks.
  Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml
  Resources/Prototypes/Catalog/Fills/Lockers/engineer.yml
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Catalog/Fills/Lockers/security.yml
  Resources/Prototypes/Catalog/Fills/Lockers/suit_storage.yml
Labels: No C#, Needs Discussion, Undergoing maintainer discussion
