Repository RonRonstation/ronstation, pull requests merged in 2025-09, with the labels that each got.

#377 Cluster-II BSO update
  Resources/Maps/Ronstation/cluster-2.yml
Labels: Changes: No C#, S: Needs Review, Changes: Map, size/XL

#376 Feint smartfridge hotfix
  Resources/Maps/_Ronstation/feint.yml
Labels: Changes: No C#, S: Needs Review, Changes: Map, size/L

#380 Update SpaceLaw.xml
  Resources/ServerInfo/_Ronstation/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml
Labels: Changes: No C#, S: Needs Review, S: Untriaged, size/XS

#379 AI navmap done right
  Content.Client/Pinpointer/UI/NavMapControl.cs
  Content.Client/Silicons/StationAi/StationAiOverlay.cs
Labels: S: Needs Review, S: Untriaged, size/M

#384 Disable randomized characters & mob collisions on the dev build in config
  Resources/ConfigPresets/Build/development.toml
Labels: Changes: No C#, S: Needs Review, S: Untriaged

#391 Make butterflies Zombie Immune
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Labels: Changes: No C#, S: Needs Review, size/XS

#374 Vampire Feed action
  Content.Client/_Ronstation/Vampire/EntitySystems/VampireSystem.cs
  Content.Server/_Ronstation/Vampire/EntitySystems/VampireSystem.Abilities.cs
  Content.Server/_Ronstation/Vampire/EntitySystems/VampireSystem.cs
  Content.Shared/_Ronstation/Vampire/Components/VampireComponent.cs
  Content.Shared/_Ronstation/Vampire/Components/VampireFeedComponent.cs
  Content.Shared/_Ronstation/Vampire/EntitySystems/SharedVampireSystem.cs
  Content.Shared/_Ronstation/Vampire/VampireFeedEvent.cs
  Resources/Locale/en-US/_Ronstation/alerts/alerts.ftl
  Resources/Locale/en-US/_Ronstation/vampire/vampire.ftl
  Resources/Prototypes/_Ronstation/Actions/vampire.yml
  Resources/Prototypes/_Ronstation/Alerts/vampire.yml
  Resources/Prototypes/_Ronstation/GameRules/subgamemodes.yml
  Resources/Prototypes/_Ronstation/Roles/MindRoles/mind_roles.yml
  Resources/Prototypes/ai_factions.yml
  Resources/Textures/_Ronstation/Interface/Actions/feed.rsi/icon-on.png
  Resources/Textures/_Ronstation/Interface/Actions/feed.rsi/icon.png
  Resources/Textures/_Ronstation/Interface/Actions/feed.rsi/meta.json
  Resources/Textures/_Ronstation/Interface/Misc/job_icons.rsi/meta.json
Labels: Changes: Sprites, S: Needs Review, P3: Standard, A: Roundflow/Antag, size/M

#386 Randomized centcomm
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Content.Server/Shuttles/Components/StationCentcommComponent.cs
  Content.Server/Shuttles/Systems/EmergencyShuttleSystem.cs
  Content.Server/_Ronstation/GameTicking/Commands/ForceCCCommand.cs
  Content.Shared/_Ronstation/CCVars.cs
  Resources/Locale/en-US/_Ronstation/commands/force-centcomm-command.ftl
  Resources/Maps/_Ronstation/CentComm/budget.yml
  Resources/Prototypes/_Ronstation/Maps/CentComm/budget.yml
  Resources/Prototypes/_Ronstation/centcomms.yml
Labels: Changes: Map, P4: Fluff, Fun: Awesome, size/L

#390 Let borgs equip trinket plushies in loadouts!
  Content.Client/Lobby/LobbyUIController.cs
  Content.Server/Station/Systems/StationSpawningSystem.cs
  Resources/Prototypes/Loadouts/Miscellaneous/trinkets.yml
  Resources/Prototypes/Loadouts/role_loadouts.yml
  Resources/Prototypes/_Ronstation/Loadouts/Groups/Science/borg.yml
  Resources/Prototypes/_Ronstation/Loadouts/Role/Science/borg.yml
  Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/arachind.yml
  Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/atmosian.yml
  Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/bee.yml
  Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/diona.yml
  Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/hampter.yml
  Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/human.yml
  Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/lizard.yml
  Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/moth.yml
  Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/nuke.yml
  Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/penguin.yml
  Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/slime.yml
  Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/space_lizard.yml
  Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/vox.yml
Labels: S: Needs Review, P4: Fluff, A: Character/Species, A: Silicons, size/M, DB: Beginner Friendly

#404 Disables Vulpkanin
  Resources/Prototypes/Species/species_weights.yml
  Resources/Prototypes/Species/vulpkanin.yml
Labels: Changes: No C#, S: Needs Review, size/XS
