Repository RonRonstation/ronstation, pull requests merged in 2025-06, with the labels that each got.

#231 Changes to Wizard smite to be less frustrating and round-removey
  Content.Shared/Magic/Events/CellularSmiteSpellEvent.cs
  Content.Shared/Magic/SharedMagicSystem.cs
  Resources/Locale/en-US/store/spellbook-catalog.ftl
  Resources/Prototypes/Catalog/spellbook_catalog.yml
  Resources/Prototypes/Magic/touch_spells.yml
Labels: P3: Standard, V: Successful, size/S, A: Roundflow/Antag, T: Balance Changes

#265 Fix C.Smite to remove unneeded components/fit the new format for spell actions
  Resources/Prototypes/Magic/touch_spells.yml
Labels: T: Bug, Changes: No C#, P3: Standard, size/XS

#250 Add lockers to the Staff of Animation spell's blacklist
  Resources/Prototypes/Magic/animate_spell.yml
Labels: Changes: No C#, P2: Raised, A: Roundflow/Antag, T: Balance Changes, size/XS

#247 Removes salt ore deposits from expeditions and lowers the chance of it appearing in asteroids
  Resources/Prototypes/Procedural/Magnet/asteroid_ore_gens.yml
  Resources/Prototypes/Procedural/biome_ore_templates.yml
  Resources/Prototypes/Procedural/biome_ore_templates_low.yml
  Resources/Prototypes/Procedural/salvage_loot.yml
Labels: Changes: No C#, P3: Standard, V: Successful, size/S, A: Cargo/Salvage, T: Balance Changes

#266 Make tourniquets actually good and useful and accessible
  Resources/Locale/en-US/stack/stacks.ftl
  Resources/Prototypes/Entities/Objects/Specific/Medical/healing.yml
  Resources/Prototypes/Recipes/Lathes/Packs/security.yml
  Resources/Prototypes/Recipes/Lathes/security.yml
  Resources/Prototypes/Stacks/medical_stacks.yml
Labels: Changes: No C#, S: Untriaged, size/S

#270 5-07 Paradoxical Existence space law criminal charge
  Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLCrimeList.xml
Labels: Changes: No C#

#267 Revert reversion of new cryonics
  Resources/Changelog/Changelog.yml
  Resources/Locale/en-US/reagents/meta/medicine.ftl
  Resources/Prototypes/Reagents/medicine.yml
  Resources/Prototypes/Recipes/Reactions/medicine.yml
Labels: Changes: No C#, P3: Standard, A: Medical, size/M

#282 Part One of AI Cosmetics. Hologram Package
  Resources/Locale/en-US/silicons/station-ai.ftl
  Resources/Prototypes/AppearanceCustomization/station_ai.yml
  Resources/Textures/Mobs/Silicon/holograms.rsi/ai_arach.png
  Resources/Textures/Mobs/Silicon/holograms.rsi/ai_clown.png
  Resources/Textures/Mobs/Silicon/holograms.rsi/ai_dionanymph.png
  Resources/Textures/Mobs/Silicon/holograms.rsi/ai_lizard.png
  Resources/Textures/Mobs/Silicon/holograms.rsi/ai_moth.png
  Resources/Textures/Mobs/Silicon/holograms.rsi/ai_mothroach.png
  Resources/Textures/Mobs/Silicon/holograms.rsi/ai_vox.png
  Resources/Textures/Mobs/Silicon/holograms.rsi/ai_weh.png
  Resources/Textures/Mobs/Silicon/holograms.rsi/meta.json
Labels: Changes: Sprites, Changes: No C#, S: Needs Review, P3: Standard

#293 Reorganize fork folders.
  Content.Server/_Impstation/Containers/AntiTamper/AntiTamperComponent.cs
  Content.Server/_Impstation/Containers/AntiTamper/AntiTamperSystem.cs
  Content.Shared/_Impstation/Containers/AntiTamper/AntiTamperDisarmDoAfterEvent.cs
  Resources/Locale/en-US/_Impstation/anti-tamper.ftl
  Resources/Prototypes/_Impstation/Catalog/Cargo/cargo_emergency.yml
  Resources/Prototypes/_Impstation/Catalog/Fills/Crates/emergency.yml
  Resources/Prototypes/_Impstation/Entities/Objects/Weapons/Guns/Battery/emergencylaser.yml
  Resources/Prototypes/_Impstation/Entities/Objects/Weapons/Guns/Projectiles/hitscan.yml
  Resources/Textures/_Impstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/base.png
  Resources/Textures/_Impstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/equipped-BACKPACK.png
  Resources/Textures/_Impstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/equipped-SUITSTORAGE.png
  Resources/Textures/_Impstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/icon.png
  Resources/Textures/_Impstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/inhand-left.png
  Resources/Textures/_Impstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/inhand-right.png
  Resources/Textures/_Impstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/mag-unshaded-1.png
  Resources/Textures/_Impstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/mag-unshaded-2.png
  Resources/Textures/_Impstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/mag-unshaded-3.png
  Resources/Textures/_Impstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/mag-unshaded-4.png
  Resources/Textures/_Impstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/meta.json
  Resources/Textures/_Impstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/wielded-inhand-left.png
  Resources/Textures/_Impstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/wielded-inhand-right.png
Labels: Changes: Sprites, P3: Standard, T: Cleanup, size/XS, A: Legal

#298 Clarification of licenses
  LEGAL.md
  LICENSE-MIT.TXT
  README.md
Labels: P0: Critical, T: Cleanup, A: Legal

#301 Remove unneeded CCVar.
  Content.Shared/_Goobstation/CCVars/CCVars.Goob.cs
Labels: P3: Standard, S: Untriaged, size/S, T: Cleanup

#257 Enrobustify Vox slightly
  Resources/Prototypes/Entities/Mobs/Species/vox.yml
  Resources/ServerInfo/Guidebook/Mobs/Vox.xml
Labels: Changes: No C#, size/S

#303 Relocates maps, then adds headers.
  Resources/Maps/Ronstation/atlas-2.yml
  Resources/Maps/Ronstation/cluster-2.yml
  Resources/Maps/Ronstation/saltern-2.yml
  Resources/Maps/_Ronstation/Shuttles/mining.yml
  Resources/Maps/_Ronstation/atlas-2.yml
  Resources/Prototypes/Ronstation/Maps/atlas-2.yml
  Resources/Prototypes/Ronstation/Maps/cluster-2.yml
  Resources/Prototypes/Ronstation/Maps/saltern-2.yml
  Resources/map_attributions.txt
Labels: Changes: No C#, S: Needs Review, P3: Standard, Changes: Map, A: Accessibility, A: Mapping, T: Cleanup, A: Legal
