Repository RonRonstation/ronstation, pull requests merged in 2025-05, with the labels that each got.

#214 Fix duplicate reagents
  Resources/Locale/en-US/_Ronstation/reagents/meta/medicine.ftl
  Resources/Prototypes/_Ronstation/Reagents/medicine.yml
  Resources/Prototypes/_Ronstation/Recipes/Reactions/medicine.yml
Labels: T: Bug, Changes: No C#, size/S

#212 Some more map updates.
  Resources/Maps/_Ronstation/cluster-2.yml
  Resources/Maps/_Ronstation/saltern-2.yml
Labels: Changes: No C#, P2: Raised, Changes: Map, A: Mapping, T: New Feature, size/XL

#213 Tracking implant revert
  Resources/Prototypes/Entities/Objects/Misc/subdermal_implants.yml
Labels: Changes: No C#, P3: Standard, T: Balance Changes, size/XS

#219 Increased Beaker Capacity
  Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
Labels: Changes: No C#, P3: Standard, A: Medical, T: Balance Changes

#215 Revert "PKA Modkits + Rebalance (#31247)"
  Resources/Prototypes/Entities/Markers/Spawners/Random/Salvage/tables_loot.yml
  Resources/Prototypes/Entities/Objects/Tools/pka_upgrade.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/base_pka.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/pka.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Recipes/Lathes/Packs/science.yml
  Resources/Prototypes/Recipes/Lathes/Packs/shared.yml
  Resources/Prototypes/Recipes/Lathes/salvage.yml
  Resources/Prototypes/Research/arsenal.yml
Labels: Changes: Sprites, Changes: No C#, S: Needs Review, S: Untriaged, S: Undergoing maintainer discussion, A: Cargo/Salvage, A: Combat, size/M

#228 Remove imprinter from lathe pack.
  Resources/Prototypes/Recipes/Lathes/Packs/cargo.yml
Labels: Changes: No C#, P2: Raised, A: Cargo/Salvage, T: Balance Changes, size/XS

#230 Revert cargo slip change
  Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Labels: Changes: Sprites, Changes: No C#, S: Untriaged, Changes: UI, size/S, Changes: Audio

#235 Added Overridesell(Engineering) component to Storage Canisters.
  Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml
Labels: Changes: No C#, P2: Raised, A: Cargo/Salvage, A: Engineering, T: Balance Changes, size/XS

#220 Updates to Saltern-2.
  Resources/Maps/_Ronstation/saltern-2.yml
Labels: Changes: No C#, S: Needs Review, Changes: Map, P1: High, A: Mapping, size/XL

#234 Gas price
  Resources/Prototypes/Atmospherics/gases.yml
Labels: Changes: No C#, S: Untriaged, size/XS

#222 The Mop Spear PR
  Resources/Locale/en-US/recipes/tags.ftl
  Resources/Prototypes/Entities/Objects/Weapons/Melee/spear.yml
  Resources/Prototypes/Recipes/Construction/Graphs/weapons/spear.yml
  Resources/Prototypes/Recipes/Construction/weapons.yml
  Resources/Textures/Objects/Weapons/Melee/spearmop.rsi/equipped-BACKPACK.png
  Resources/Textures/Objects/Weapons/Melee/spearmop.rsi/equipped-SUITSTORAGE.png
  Resources/Textures/Objects/Weapons/Melee/spearmop.rsi/equipped-back-fill-1.png
  Resources/Textures/Objects/Weapons/Melee/spearmop.rsi/equipped-suitstorage-fill-1.png
  Resources/Textures/Objects/Weapons/Melee/spearmop.rsi/fill-1.png
  Resources/Textures/Objects/Weapons/Melee/spearmop.rsi/fill-2.png
  Resources/Textures/Objects/Weapons/Melee/spearmop.rsi/fill-3.png
  Resources/Textures/Objects/Weapons/Melee/spearmop.rsi/inhand-left-fill-1.png
  Resources/Textures/Objects/Weapons/Melee/spearmop.rsi/inhand-left.png
  Resources/Textures/Objects/Weapons/Melee/spearmop.rsi/inhand-right-fill-1.png
  Resources/Textures/Objects/Weapons/Melee/spearmop.rsi/inhand-right.png
  Resources/Textures/Objects/Weapons/Melee/spearmop.rsi/meta.json
  Resources/Textures/Objects/Weapons/Melee/spearmop.rsi/spearmop.png
  Resources/Textures/Objects/Weapons/Melee/spearmop.rsi/wielded-inhand-left-fill-1.png
  Resources/Textures/Objects/Weapons/Melee/spearmop.rsi/wielded-inhand-left.png
  Resources/Textures/Objects/Weapons/Melee/spearmop.rsi/wielded-inhand-right-fill-1.png
  Resources/Textures/Objects/Weapons/Melee/spearmop.rsi/wielded-inhand-right.png
Labels: Changes: Sprites, Changes: No C#, S: Needs Review, P4: Fluff, T: New Feature, size/M

#237 Role timers Rework
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Ronstation/Roles/Jobs/Command/blueshield_officer.yml
Labels: Changes: No C#, V: Successful, size/S, P1: High, A: Roleplay/Lore, T: Balance Changes

#238 remove extended from the secret pool
  Resources/Prototypes/secret_weights.yml
Labels: Changes: No C#, P2: Raised, V: Successful, T: Balance Changes, T: Performance, size/XS

#240 Removes the crazy ass smuggled crate
  Resources/Prototypes/_Ronstation/Catalog/Cargo/cargo_smuggled.yml
  Resources/Prototypes/_Ronstation/Catalog/Fills/Crates/smuggled.yml
Labels: Changes: No C#, S: Untriaged, size/S

#242 Adds External access to the default access for Paramedics
  Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
Labels: Changes: No C#, P3: Standard, A: Medical, T: Balance Changes, size/XS

#243 init
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
Labels: Changes: No C#, S: Untriaged, size/XS

#249 ATTEMPT TWO AT FIXING ADDING MORE HAIRS
  Resources/Locale/en-US/_Ronstation/accessories/human-hair.ftl
  Resources/Locale/en-US/_Ronstation/accessories/vox-facial-hair.ftl
  Resources/Locale/en-US/_Ronstation/accessories/vox-hair.ftl
  Resources/Prototypes/_Ronstation/Entities/Mobs/Customization/Markings/human_hair.yml
  Resources/Prototypes/_Ronstation/Entities/Mobs/Customization/Markings/vox_facial_hair.yml
  Resources/Prototypes/_Ronstation/Entities/Mobs/Customization/Markings/vox_hair.yml
  Resources/Textures/_Ronstation/Mobs/Customization/human_hair.rsi/longbangs.png
  Resources/Textures/_Ronstation/Mobs/Customization/human_hair.rsi/meta.json
  Resources/Textures/_Ronstation/Mobs/Customization/human_hair.rsi/ponytailwithbows.png
  Resources/Textures/_Ronstation/Mobs/Customization/human_hair.rsi/zebra.png
  Resources/Textures/_Ronstation/Mobs/Customization/vox_facial_hair.rsi/meta.json
  Resources/Textures/_Ronstation/Mobs/Customization/vox_facial_hair.rsi/voxsideburns.png
  Resources/Textures/_Ronstation/Mobs/Customization/vox_hair.rsi/flowingbraids.png
  Resources/Textures/_Ronstation/Mobs/Customization/vox_hair.rsi/meta.json
Labels: Changes: Sprites, Changes: No C#, size/S, P4: Fluff, A: Art, A: Character/Species, T: New Feature

#251 Gas Price Balance
  Resources/Prototypes/Atmospherics/gases.yml
  Resources/Prototypes/Entities/Objects/Specific/Xenoarchaeology/artifact_equipment.yml
Labels: Changes: No C#, size/S

#258 Remove requirements of using removed machine parts.
  Resources/Prototypes/Ronstation/Entities/Objects/Devices/Circuitboards/engines.yml
  Resources/Prototypes/Ronstation/Entities/Objects/Devices/Circuitboards/production.yml
  Resources/Prototypes/_Ronstation/Entities/Objects/Devices/Circuitboards/Machine/production.yml
Labels: T: Bug, Changes: No C#, size/S, P1: High

#259 add socks
  Resources/Locale/en-US/_Ronstation/accessories/socks.ftl
  Resources/Prototypes/_Ronstation/Entities/Mobs/Customization/Markings/socks.yml
  Resources/Textures/_Ronstation/Mobs/Customization/socks.rsi/leftsock.png
  Resources/Textures/_Ronstation/Mobs/Customization/socks.rsi/meta.json
  Resources/Textures/_Ronstation/Mobs/Customization/socks.rsi/rightsock.png
  Resources/Textures/_Ronstation/Mobs/Customization/socks.rsi/voxleftsock.png
  Resources/Textures/_Ronstation/Mobs/Customization/socks.rsi/voxrightsock.png
Labels: Changes: Sprites, Changes: No C#, size/S, P4: Fluff, A: Character/Species, T: New Feature

#254 Reverts changes to the salvage loot tables
  Resources/Prototypes/Procedural/Magnet/space_debris_templates.yml
  Resources/Prototypes/Procedural/vgroid.yml
Labels: Changes: No C#, P3: Standard, size/S, A: Cargo/Salvage, T: Balance Changes

#221 Readds turtleneck sweater jumpsuits/skirts
  Resources/Prototypes/Catalog/VendingMachines/Inventories/winterdrobe.yml
  Resources/Prototypes/Entities/Clothing/Uniforms/color_turtlenecks.yml
  Resources/Prototypes/Entities/Clothing/Uniforms/color_turtlenecks_skirt.yml
  Resources/Textures/Clothing/Uniforms/Jumpskirt/color_turtle.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/color_turtle.rsi/icon.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/color_turtle.rsi/inhand-left.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/color_turtle.rsi/inhand-right.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/color_turtle.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpskirt/color_turtle.rsi/skirt-equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/color_turtle.rsi/skirt-icon.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/color_turtle.rsi/skirt-inhand-left.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/color_turtle.rsi/skirt-inhand-right.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/color_turtle.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/color_turtle.rsi/icon.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/color_turtle.rsi/inhand-left.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/color_turtle.rsi/inhand-right.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/color_turtle.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/color_turtle.rsi/trousers-equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/color_turtle.rsi/trousers-icon.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/color_turtle.rsi/trousers-inhand-left.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/color_turtle.rsi/trousers-inhand-right.png
Labels: Changes: Sprites, Changes: No C#, P4: Fluff, T: New Feature, size/L

#255 more saltern changes
  Resources/Maps/_Ronstation/saltern-2.yml
Labels: Changes: No C#, P3: Standard, Changes: Map, V: Successful, A: Mapping, size/XL

#264 Added role chameleon outfits.
  Resources/Prototypes/Ronstation/Roles/Jobs/CentCom/centcomblueshield.yml
  Resources/Prototypes/Ronstation/Roles/Jobs/Command/blueshield_officer.yml
Labels: T: Bug, Changes: No C#, P3: Standard, S: Untriaged, size/S
