Repository RonRonstation/ronstation, pull requests merged in 2025-03, with the labels that each got.

#182 Restore imprinter recipe on autolathes
  Resources/Prototypes/Recipes/Lathes/Packs/cargo.yml
  Resources/Prototypes/_Ronstation/Recipes/Lathes/electronics.yml
Labels: Changes: No C#, S: Untriaged, size/XS

#183 Replaced Substation and APC sprites.
  Content.Client/Power/APC/ApcVisualizerComponent.cs
  Resources/Prototypes/Entities/Structures/Power/apc.yml
  Resources/Prototypes/Entities/Structures/Power/substation.yml
Labels: S: Needs Review, S: Untriaged, size/S

#188 Fix .TXT prefix.
  LEGAL.md
  LICENSE-AGPL.TXT
Labels: T: Bug, Changes: No C#, S: Needs Review, P4: Fluff, size/XS

#190 Changed spider ghost role to be free agent
  Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Labels: Changes: No C#, S: Needs Review, P4: Fluff, T: Balance Changes, T: Cleanup, size/XS

#198 cluster tweaks & fixes
  Resources/Maps/Ronstation/cluster-2.yml
  Resources/Prototypes/Ronstation/Maps/cluster-2.yml
Labels: Changes: No C#, P3: Standard, Changes: Map, A: Mapping, size/L

#197 fixes lawyer job on atlas
  Resources/Prototypes/Ronstation/Maps/atlas-2.yml
Labels: Changes: No C#, S: Untriaged, size/XS

#196 makes armoury-locked crates actually secure + adds emergency laser rifle crate
  Content.Server/Containers/AntiTamper/AntiTamperComponent.cs
  Content.Server/Containers/AntiTamper/AntiTamperSystem.cs
  Content.Shared/Containers/AntiTamper/AntiTamperDisarmDoAfterEvent.cs
  Resources/Locale/en-US/anti-tamper.ftl
  Resources/Prototypes/Entities/Structures/Storage/Crates/crates.yml
  Resources/Prototypes/_Ronstation/Catalog/Cargo/cargo_emergency.yml
  Resources/Prototypes/_Ronstation/Catalog/Fills/Crates/emergency.yml
  Resources/Prototypes/_Ronstation/Entities/Objects/Weapons/Guns/Battery/emergencylaser.yml
  Resources/Prototypes/_Ronstation/Entities/Objects/Weapons/Guns/Projectiles/hitscan.yml
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/base.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/equipped-BACKPACK.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/equipped-SUITSTORAGE.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/icon.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/inhand-left.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/inhand-right.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/mag-unshaded-1.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/mag-unshaded-2.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/mag-unshaded-3.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/mag-unshaded-4.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/meta.json
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/wielded-inhand-left.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Battery/emergency_laser_gun.rsi/wielded-inhand-right.png
Labels: Changes: Sprites, P3: Standard, S: Needs Discussion, A: Cargo/Salvage, A: Security, T: Balance Changes, size/M

#194 Removed survival again.
  Resources/Prototypes/secret_weights.yml
Labels: Changes: No C#, S: Needs Review, P4: Fluff, T: Balance Changes, size/XS

#195 Add paper printer and related papers.
  Resources/Locale/en-US/_Ronstation/paper/attributions.yml
  Resources/Locale/en-US/_Ronstation/paper/paper-forms.ftl
  Resources/Maps/Ronstation/cluster-2.yml
  Resources/Prototypes/Entities/Objects/Misc/paper.yml
  Resources/Prototypes/_Ronstation/Catalog/Fills/Paper/forms.yml
  Resources/Prototypes/_Ronstation/Entities/Objects/Devices/Circuitboards/Machine/production.yml
  Resources/Prototypes/_Ronstation/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/_Ronstation/Recipes/Lathes/Packs/printer.yml
  Resources/Prototypes/_Ronstation/Recipes/Lathes/printer.yml
Labels: Changes: No C#, S: Needs Review, P3: Standard, S: Untriaged, Changes: Map, A: Roleplay/Lore, T: New Feature

#193 Disable event spells.
  Resources/Prototypes/Catalog/spellbook_catalog.yml
Labels: S: Needs Review, size/S, P1: High, A: Roleplay/Lore, T: Balance Changes

#199 Edited salvage shuttle.
  Resources/Locale/en-US/_Ronstation/holopad/holopad.ftl
  Resources/Maps/_Ronstation/Shuttles/mining.yml
  Resources/Prototypes/Entities/Stations/base.yml
  Resources/Prototypes/_Ronstation/Entities/Structures/Machines/holopad.yml
Labels: Changes: No C#, S: Needs Review, Changes: Map, P1: High, A: Cargo/Salvage, A: Mapping, size/L

#201 Readd gas tanks to engineer lockers.
  Resources/Prototypes/Catalog/Fills/Lockers/engineer.yml
Labels: Changes: No C#, S: Untriaged, S: Awaiting Changes, size/XS
