Repository RonRonstation/ronstation, pull requests merged in 2025-07, with the labels that each got.

#304 Reorganizing Ronstation content (and adding appropriate sublicense headers) PT. 3
  Content.Benchmarks/MapLoadBenchmark.cs
  Content.Server/StationEvents/Events/BureaucraticErrorRule.cs
  Resources/Locale/en-US/research/technologies.ftl
  Resources/Locale/en-US/station-events/events/bureaucratic-error.ftl
  Resources/Locale/en-US/store/uplink-catalog.ftl
  Resources/Prototypes/Atmospherics/gases.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/Salvage/tables_loot.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/pie.yml
  Resources/Prototypes/Entities/Objects/Misc/subdermal_implants.yml
  Resources/Prototypes/Entities/Objects/Specific/Medical/defib.yml
  Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/base_pka.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Launchers/launchers.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
  Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml
  Resources/Prototypes/Procedural/Magnet/asteroid_ore_gens.yml
  Resources/Prototypes/Procedural/biome_ore_templates.yml
  Resources/Prototypes/Procedural/biome_ore_templates_low.yml
  Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
  Resources/Prototypes/Recipes/Lathes/Packs/medical.yml
  Resources/Prototypes/Recipes/Lathes/Packs/science.yml
  Resources/Prototypes/Recipes/Lathes/Packs/shared.yml
  Resources/Prototypes/Recipes/Lathes/medical.yml
  Resources/Prototypes/Recipes/Lathes/salvage.yml
  Resources/Prototypes/Research/arsenal.yml
  Resources/Prototypes/Research/civilianservices.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Ronstation/Roles/Jobs/Command/blueshield_officer.yml
  Resources/Prototypes/_Ronstation/Recipes/Cooking/meal_recipes.yml
  Resources/Prototypes/_Ronstation/Recipes/Lathes/comupter_boards.yml
  Resources/Prototypes/_Ronstation/Recipes/Lathes/machine_boards.yml
  Resources/Prototypes/secret_weights.yml
Labels: Changes: No C#, P3: Standard, T: Cleanup, size/M, A: Legal

#308 The Great Reorganization PT 4
  Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
  Resources/Locale/en-US/tools/tool-qualities.ftl
  Resources/Prototypes/Catalog/VendingMachines/Inventories/chemvend.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/seeds.yml
  Resources/Prototypes/Catalog/spellbook_catalog.yml
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
  Resources/Prototypes/Entities/Mobs/NPCs/slimes.yml
  Resources/Prototypes/Entities/Objects/Misc/paper.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml
  Resources/Prototypes/Entities/Stations/base.yml
  Resources/Prototypes/Entities/Structures/Storage/Crates/crates.yml
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/Recipes/Lathes/Packs/biogen.yml
  Resources/Prototypes/Tiles/plating.yml
  Resources/Prototypes/_Ronstation/tool_qualities.yml
  Resources/Prototypes/tool_qualities.yml
Labels: Changes: No C#, S: Needs Review, P3: Standard, size/S, T: Cleanup, A: Legal

#309 (Bugfix) Add whistle to objectivegroups, remove now gone warden hat objective
  Resources/Prototypes/Objectives/objectiveGroups.yml
Labels: T: Bug, Changes: No C#, S: Needs Review, P3: Standard, A: Roundflow/Antag, size/XS

#312 Fix inline licensing comments appearing in some in-game text
  Resources/Locale/en-US/_Ronstation/ghost/ghost-role-component.ftl
  Resources/Locale/en-US/_Ronstation/research/technologies.ftl
  Resources/Locale/en-US/_Ronstation/station-events/events/bureaucratic-error.ftl
  Resources/Locale/en-US/_Ronstation/store/uplink-catalog.ftl
  Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
  Resources/Locale/en-US/research/technologies.ftl
  Resources/Locale/en-US/station-events/events/bureaucratic-error.ftl
  Resources/Locale/en-US/store/uplink-catalog.ftl
Labels: T: Bug, Changes: No C#, S: Needs Review, P3: Standard, size/S, T: Cleanup

#311 Raises minimum players required for the wizard spawn to 25
  Resources/Prototypes/GameRules/events.yml
Labels: Changes: No C#, S: Needs Review, P3: Standard, A: Roundflow/Antag, size/XS

#315 Deckard & speedloader rework+resprite
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/SpeedLoaders/magnum.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Revolvers/revolvers.yml
  Resources/Prototypes/_Ronstation/Entities/Objects/Specific/deckardbox.yml
  Resources/Prototypes/_Ronstation/Entities/Objects/Weapons/Guns/Ammunition/SpeedLoaders/deckard.yml
  Resources/Textures/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Pistol/pistol_speed_loader.rsi/meta.json
  Resources/Textures/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Pistol/pistol_speed_loader.rsi/piercing-1.png
  Resources/Textures/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Pistol/pistol_speed_loader.rsi/piercing-2.png
  Resources/Textures/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Pistol/pistol_speed_loader.rsi/piercing-3.png
  Resources/Textures/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Pistol/pistol_speed_loader.rsi/piercing-4.png
  Resources/Textures/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Pistol/pistol_speed_loader.rsi/piercing-5.png
  Resources/Textures/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Pistol/pistol_speed_loader.rsi/piercing-6.png
  Resources/Textures/_Ronstation/Objects/Storage/deckardbox.rsi/closed.png
  Resources/Textures/_Ronstation/Objects/Storage/deckardbox.rsi/deckard.png
  Resources/Textures/_Ronstation/Objects/Storage/deckardbox.rsi/inhand-left.png
  Resources/Textures/_Ronstation/Objects/Storage/deckardbox.rsi/inhand-right.png
  Resources/Textures/_Ronstation/Objects/Storage/deckardbox.rsi/loader1.png
  Resources/Textures/_Ronstation/Objects/Storage/deckardbox.rsi/loader2.png
  Resources/Textures/_Ronstation/Objects/Storage/deckardbox.rsi/meta.json
  Resources/Textures/_Ronstation/Objects/Storage/deckardbox.rsi/open.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Deckard/deckard_speed_loader.rsi/base-1.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Deckard/deckard_speed_loader.rsi/base-2.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Deckard/deckard_speed_loader.rsi/base-3.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Deckard/deckard_speed_loader.rsi/base-4.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Deckard/deckard_speed_loader.rsi/base-5.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Deckard/deckard_speed_loader.rsi/base.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Deckard/deckard_speed_loader.rsi/icon.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Deckard/deckard_speed_loader.rsi/inhand-left.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Deckard/deckard_speed_loader.rsi/inhand-right.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Deckard/deckard_speed_loader.rsi/meta.json
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Revolvers/deckard.rsi/base.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Revolvers/deckard.rsi/equipped-BELT.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Revolvers/deckard.rsi/equipped-SUITSTORAGE.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Revolvers/deckard.rsi/inhand-left.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Revolvers/deckard.rsi/inhand-right.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Revolvers/deckard.rsi/mag-unshaded-0.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Revolvers/deckard.rsi/mag-unshaded-1.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Revolvers/deckard.rsi/mag-unshaded-2.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Revolvers/deckard.rsi/mag-unshaded-3.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Revolvers/deckard.rsi/mag-unshaded-4.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Revolvers/deckard.rsi/meta.json
Labels: Changes: Sprites, Changes: No C#, S: Needs Review, P4: Fluff, Fun: Awesome, size/M

#319 DrinkShaker and DrinkTeapot now are 120u instead of 100u
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_special.yml
Labels: Changes: No C#, S: Needs Review, size/XS

#318 The Negotiator
  Resources/Locale/en-US/_Ronstation/objectives/conditions/steal-target-groups.ftl
  Resources/Locale/en-US/objectives/conditions/steal-target-groups.ftl
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Catalog/Fills/Lockers/security.yml
  Resources/Prototypes/Objectives/traitor.yml
  Resources/Prototypes/Recipes/Lathes/Packs/security.yml
  Resources/Prototypes/_Ronstation/Entities/Objects/Weapons/Guns/Ammunition/Magazines/magnum.yml
  Resources/Prototypes/_Ronstation/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
  Resources/Prototypes/_Ronstation/Objectives/stealTargetGroups.yml
  Resources/Prototypes/_Ronstation/Objectives/traitor.yml
  Resources/Prototypes/_Ronstation/Recipes/Lathes/ammo.yml
  Resources/Prototypes/_Ronstation/tags.yml
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/Magazine/Magnum/negotiator.rsi/base.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/Magazine/Magnum/negotiator.rsi/icon.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/Magazine/Magnum/negotiator.rsi/inhand-left.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/Magazine/Magnum/negotiator.rsi/inhand-right.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/Magazine/Magnum/negotiator.rsi/mag-1.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/Magazine/Magnum/negotiator.rsi/mag-2.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/Magazine/Magnum/negotiator.rsi/mag-3.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/Magazine/Magnum/negotiator.rsi/mag-4.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/Magazine/Magnum/negotiator.rsi/mag-5.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/Magazine/Magnum/negotiator.rsi/meta.json
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Pistols/negotiator.rsi/base.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Pistols/negotiator.rsi/bolt-open.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Pistols/negotiator.rsi/equipped-BELT.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Pistols/negotiator.rsi/equipped-SUITSTORAGE.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Pistols/negotiator.rsi/icon.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Pistols/negotiator.rsi/inhand-left.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Pistols/negotiator.rsi/inhand-right.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Pistols/negotiator.rsi/mag-0.png
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Pistols/negotiator.rsi/meta.json
Labels: Changes: Sprites, Changes: No C#, P3: Standard, A: Security, T: New Feature, size/M
