Repository RonRonstation/ronstation, pull requests merged in 2025-04, with the labels that each got.

#203 Rules Change
  Content.Shared/CCVar/CCVars.Server.cs
  Resources/Prototypes/Guidebook/rules.yml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC0.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC1.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC10.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC2.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC3.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC4.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC5.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC6.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC7.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC8.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC9.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR0.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR1.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR2.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR3.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR4.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR5.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR6.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR7.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RonstationRules.xml
Labels: P0: Critical, A: Rules, T: Of Admin Interest, size/M

#207 Update
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC0.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC10.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC2.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC3.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC5.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC6.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC7.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC8.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC9.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR0.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR1.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR2.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR3.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR4.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR5.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR6.xml
  Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR7.xml
Labels: Changes: No C#, S: Untriaged, size/S, P1: High, A: Rules, T: Of Admin Interest, S: Approved

#206 Fix heccdiver and CC blueshield names.
  Resources/Prototypes/Ronstation/Entities/Mobs/Player/humanoid.yml
Labels: T: Bug, Changes: No C#, S: Needs Review, P2: Raised, S: Untriaged, size/XS

#208 Fix arbitrage issue in ore processor machine board.
  Resources/Prototypes/Ronstation/Entities/Objects/Devices/Circuitboards/production.yml
Labels: T: Bug, Changes: No C#, S: Needs Review, P1: High, size/XS

#211 Fix missing recipes.
  Resources/Prototypes/Ronstation/Recipes/Lathes/comupter_boards.yml
  Resources/Prototypes/Ronstation/Recipes/Lathes/electronics.yml
  Resources/Prototypes/Ronstation/Recipes/Lathes/machine_boards.yml
Labels: T: Bug, P3: Standard

#209 BureaucraticErrorEvent-Tweak
  Content.Server/StationEvents/Events/BureaucraticErrorRule.cs
  Resources/Locale/en-US/station-events/events/bureaucratic-error.ftl
Labels: S: Untriaged, size/S
