Repository RonRonstation/ronstation, pull requests merged in 2025-10, with the labels that each got.

#411 Enables Vulpkanin
  Resources/Prototypes/Species/species_weights.yml
  Resources/Prototypes/Species/vulpkanin.yml
Labels: Changes: No C#, S: Needs Review, size/XS

#412 Clamp Vulp colors further
  Resources/Prototypes/Species/skin_colorations.yml
  Resources/Prototypes/Species/vulpkanin.yml
Labels: Changes: No C#, S: Needs Review, Issue: Needs replicating, S: Undergoing maintainer discussion, size/S, P4: Fluff, A: Character/Species, T: Visual Change

#413 Do NOT drink outta da toiler
  Resources/Prototypes/Entities/Structures/Furniture/toilet.yml
Labels: Changes: No C#, S: Untriaged, size/S

#415 Change Vulp Scream to default scream
  Resources/Prototypes/Voice/speech_emote_sounds.yml
Labels: Changes: No C#, S: Needs Review, S: Untriaged

#421 Bring negotiator magazines up to par with everything else
  Resources/Prototypes/Recipes/Lathes/Packs/security.yml
  Resources/Prototypes/Research/arsenal.yml
  Resources/Prototypes/_Ronstation/Entities/Objects/Weapons/Guns/Ammunition/Magazines/magnum.yml
  Resources/Prototypes/_Ronstation/Recipes/Lathes/ammo.yml
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/Magazine/Magnum/negotiator.rsi/meta.json
  Resources/Textures/_Ronstation/Objects/Weapons/Guns/Ammunition/Magazine/Magnum/negotiator.rsi/stripe.png
Labels: Changes: Sprites, Changes: No C#, S: Needs Review, P3: Standard, size/S, A: Security, T: Cleanup, T: Visual Change

#410 Kronkus products made into highly illeagal contraband
  Resources/Prototypes/_Ronstation/Entities/Objects/Specific/Hydroponics/kronkus.yml
  Resources/Prototypes/_Ronstation/Entities/Objects/Specific/Hydroponics/seeds.yml
  Resources/Prototypes/_Ronstation/Reagents/narcotics.yml
Labels: Changes: No C#, size/S

#420 Add ChairComm
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Maps/_Ronstation/CentComm/chaircomm.yml
  Resources/Prototypes/_Ronstation/Maps/CentComm/chaircomm.yml
  Resources/Prototypes/_Ronstation/centcomms.yml
Labels: S: Untriaged, Changes: Map, size/XL

#424 New Lobby Art
  Resources/Prototypes/Ronstation/lobbyscreens.yml
  Resources/Textures/Ronstation/LobbyScreens/attributions.yml
  Resources/Textures/Ronstation/LobbyScreens/halcyondays.webp
  Resources/Textures/Ronstation/LobbyScreens/halcyondays.webp.yml
Labels: Changes: No C#, S: Needs Review, size/S
